#!/usr/bin/env python3
# SUPERSEDED (2026-08-25): the shipped menu-bar/app icons are now generated by
# generate_brand_icons.py from the mascot masters in assets/brand/. Kept for reference.
"""Generate the real Flume app icon (Dock/Finder/DMG/Windows) — terracotta
background, Geist Bold "F", matching the brand tokens already documented in
context/05-conventions.md (accent #C85A3E, near-black base, Geist for UI).

This is deliberately SEPARATE from generate_icons.py, which only makes the
small monochrome menu-bar glyphs (icon.png/icon_active.png) — those must
stay flat/black/template-style for the menu bar and must never be reused as
the app icon again (that mixup is exactly why the real app icon looked
blank/wrong: the CI icon pipeline read icon.png expecting a real app icon
and got a 44x44 black mic silhouette instead).

Output: assets/app_icon.png (1024x1024) — the single source both the mac
(.icns via sips+iconutil) and Windows (.ico via PIL) icon pipelines convert
from.
"""

from PIL import Image, ImageDraw, ImageFont
import os

ASSETS_DIR = os.path.join(os.path.dirname(__file__), "..", "assets")
FONT_PATH = os.path.join(os.path.dirname(__file__), "..", "app", "assets", "fonts", "Geist_700Bold.ttf")

TERRACOTTA = (200, 90, 62, 255)   # #C85A3E — the one documented Flume accent
CREAM = (242, 242, 242, 255)      # #f2f2f2 — the documented light text/mark color


def generate_app_icon(size=1024):
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)

    margin = int(size * 0.06)
    radius = int(size * 0.22)  # macOS "squircle"-ish proportions, matches the old script's radius ratio
    draw.rounded_rectangle([margin, margin, size - margin, size - margin], radius=radius, fill=TERRACOTTA)

    font_size = int(size * 0.56)
    font = ImageFont.truetype(FONT_PATH, font_size)
    text = "F"
    bbox = draw.textbbox((0, 0), text, font=font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    # Nudge up slightly — cap-height glyphs sit visually low if centered on
    # the full bbox including descender space "F" doesn't use.
    x = (size - tw) / 2 - bbox[0]
    y = (size - th) / 2 - bbox[1] - size * 0.015
    draw.text((x, y), text, font=font, fill=CREAM)

    return img


def main():
    os.makedirs(ASSETS_DIR, exist_ok=True)
    icon = generate_app_icon(1024)
    out = os.path.join(ASSETS_DIR, "app_icon.png")
    icon.save(out)
    print(f"Generated {out}")


if __name__ == "__main__":
    main()
