/**
 * Expo config plugin — Flume Android keyboard (IME).
 *
 * android/ is gitignored and regenerated by `expo prebuild`, so the IME can't be
 * a hand-edit — this plugin re-injects it on every prebuild: it registers the
 * FlumeInputMethodService in AndroidManifest.xml and copies the Kotlin service +
 * method.xml (kept as real template files under plugins/keyboard/) into the
 * generated native tree.
 *
 * The keyboard records audio, transcribes via Groq, applies the user's dictionary
 * replacements + snippet expansion, and inserts the text. It reads its config
 * (Groq key + dictionary) from a JSON file the RN app writes to filesDir — see
 * lib/keyboardBridge.ts.
 *
 * Verifiable here only up to "prebuild applies it and the files/manifest are
 * generated". Building/running the IME needs Android Studio + a device.
 */
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const SERVICE_NAME = '.keyboard.FlumeInputMethodService';
const TEMPLATES = path.join(__dirname, 'keyboard');

function addImeService(androidManifest) {
  const app = AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);
  app.service = app.service || [];
  if (app.service.some((s) => s && s.$ && s.$['android:name'] === SERVICE_NAME)) {
    return androidManifest;
  }
  app.service.push({
    $: {
      'android:name': SERVICE_NAME,
      'android:label': 'Flume Keyboard',
      'android:permission': 'android.permission.BIND_INPUT_METHOD',
      'android:exported': 'true',
    },
    'intent-filter': [
      { action: [{ $: { 'android:name': 'android.view.InputMethod' } }] },
    ],
    'meta-data': [
      { $: { 'android:name': 'android.view.im', 'android:resource': '@xml/method' } },
    ],
  });
  return androidManifest;
}

const withFlumeKeyboard = (config) => {
  config = withAndroidManifest(config, (c) => {
    c.modResults = addImeService(c.modResults);
    return c;
  });
  config = withDangerousMod(config, [
    'android',
    (c) => {
      const root = c.modRequest.platformProjectRoot; // .../android
      const pkgDir = path.join(root, 'app/src/main/java/com/verbal/app/keyboard');
      fs.mkdirSync(pkgDir, { recursive: true });
      fs.copyFileSync(
        path.join(TEMPLATES, 'FlumeInputMethodService.kt'),
        path.join(pkgDir, 'FlumeInputMethodService.kt')
      );
      const xmlDir = path.join(root, 'app/src/main/res/xml');
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.copyFileSync(path.join(TEMPLATES, 'method.xml'), path.join(xmlDir, 'method.xml'));
      return c;
    },
  ]);
  return config;
};

module.exports = withFlumeKeyboard;
