/**
 * Expo config plugin — Flume Android keyboard (IME).
 *
 * android/ is gitignored and regenerated by `expo prebuild`, so the IME can't be
 * a hand-edit — this plugin re-injects it on every prebuild: it registers the
 * FlumeInputMethodService in AndroidManifest.xml and writes the Kotlin service +
 * method.xml into the generated native tree.
 *
 * v0 scope (FLUME_KEYBOARD_SWARM.md Agent C, first milestone): the keyboard is
 * selectable in system settings, shows a mic button, and proves text insertion
 * with a hardcoded commitText(). RECORD_AUDIO capture + the shared transcription
 * pipeline are the NEXT step (see the transcription-approach note in the spec).
 *
 * NOTE: verifiable here only up to "prebuild applies it and the manifest/files
 * are generated". Building/running the IME needs Android Studio + a device.
 */
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const SERVICE_NAME = '.keyboard.FlumeInputMethodService';

const KOTLIN_SERVICE = `package com.verbal.app.keyboard

import android.graphics.Color
import android.inputmethodservice.InputMethodService
import android.text.InputType
import android.view.Gravity
import android.view.View
import android.view.ViewGroup
import android.view.inputmethod.EditorInfo
import android.widget.Button
import android.widget.LinearLayout
import android.widget.TextView

/**
 * Flume dictation keyboard (v0). Selectable IME with a mic button. This first
 * milestone proves text insertion via a hardcoded commitText(); real audio
 * capture + transcription are wired next. Fails closed on secure fields — never
 * offers dictation in a password field.
 */
class FlumeInputMethodService : InputMethodService() {
    private var status: TextView? = null
    private var mic: Button? = null

    override fun onCreateInputView(): View {
        val root = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            gravity = Gravity.CENTER
            setBackgroundColor(Color.parseColor("#0d0c0b"))
            setPadding(48, 44, 48, 44)
            layoutParams = ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.WRAP_CONTENT
            )
        }
        mic = Button(this).apply {
            text = "Tap to dictate"
            setTextColor(Color.WHITE)
            setBackgroundColor(Color.parseColor("#E8522A"))
            setOnClickListener { onMicTap() }
        }
        status = TextView(this).apply {
            setTextColor(Color.parseColor("#8a8580"))
            textSize = 12f
            gravity = Gravity.CENTER
            setPadding(0, 24, 0, 0)
        }
        root.addView(mic)
        root.addView(status)
        return root
    }

    override fun onStartInputView(info: EditorInfo?, restarting: Boolean) {
        super.onStartInputView(info, restarting)
        if (isSecureField(info)) {
            status?.text = "Secure field — dictation disabled"
            mic?.isEnabled = false
        } else {
            status?.text = "Flume v0 — insertion test"
            mic?.isEnabled = true
        }
    }

    private fun isSecureField(info: EditorInfo?): Boolean {
        val type = info?.inputType ?: return false
        val cls = type and InputType.TYPE_MASK_CLASS
        val variation = type and InputType.TYPE_MASK_VARIATION
        val textPw = cls == InputType.TYPE_CLASS_TEXT && (
            variation == InputType.TYPE_TEXT_VARIATION_PASSWORD ||
            variation == InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD ||
            variation == InputType.TYPE_TEXT_VARIATION_WEB_PASSWORD
        )
        val numPw = cls == InputType.TYPE_CLASS_NUMBER &&
            variation == InputType.TYPE_NUMBER_VARIATION_PASSWORD
        return textPw || numPw
    }

    private fun onMicTap() {
        // v0: prove insertion works. Next: RECORD_AUDIO capture -> transcription
        // (Groq REST, mirroring lib/dictationPipeline.ts) -> commit the result.
        val ic = currentInputConnection ?: return
        ic.commitText("Hello from Flume ", 1)
    }
}
`;

const METHOD_XML = `<?xml version="1.0" encoding="utf-8"?>
<input-method xmlns:android="http://schemas.android.com/apk/res/android"
    android:settingsActivity="com.verbal.app.MainActivity">
    <subtype
        android:label="Flume"
        android:imeSubtypeMode="keyboard" />
</input-method>
`;

function addImeService(androidManifest) {
  const app = AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);
  app.service = app.service || [];
  if (app.service.some((s) => s && s.$ && s.$['android:name'] === SERVICE_NAME)) {
    return androidManifest;
  }
  app.service.push({
    $: {
      'android:name': SERVICE_NAME,
      'android:label': 'Flume Keyboard',
      'android:permission': 'android.permission.BIND_INPUT_METHOD',
      'android:exported': 'true',
    },
    'intent-filter': [
      { action: [{ $: { 'android:name': 'android.view.InputMethod' } }] },
    ],
    'meta-data': [
      { $: { 'android:name': 'android.view.im', 'android:resource': '@xml/method' } },
    ],
  });
  return androidManifest;
}

const withFlumeKeyboard = (config) => {
  config = withAndroidManifest(config, (c) => {
    c.modResults = addImeService(c.modResults);
    return c;
  });
  config = withDangerousMod(config, [
    'android',
    (c) => {
      const root = c.modRequest.platformProjectRoot; // .../android
      const pkgDir = path.join(root, 'app/src/main/java/com/verbal/app/keyboard');
      fs.mkdirSync(pkgDir, { recursive: true });
      fs.writeFileSync(path.join(pkgDir, 'FlumeInputMethodService.kt'), KOTLIN_SERVICE);

      const xmlDir = path.join(root, 'app/src/main/res/xml');
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'method.xml'), METHOD_XML);
      return c;
    },
  ]);
  return config;
};

module.exports = withFlumeKeyboard;
